apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: adsonsa/gitopsfc
  newTag: 6b61c11e525a48ce827454c313a0c99d07026978
